# This docker ci publishes a docker image to dockerhub and github packages
# there are three images published: latest, sha and version
# chksm/blstatus:latest
# chksm/blstatus:<sha>
# chksm/blstatus:<version>

name: Docker Image CI

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          version-file: version.json

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          images: |
            ghcr.io/chksm/blstatus
            chksm/blstatus
          tags: |
            latest
            ${{ steps.vars.outputs.sha_short }}
            ${{ steps.changelog.outputs.version }}