name: Publish Docker image

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          version-file: version.json

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images:
            chksm/blstatus:latest
            chksm/blstatus:${{ steps.vars.outputs.sha_short }}
            chksm/blstatus:${{ steps.changelog.outputs.version }}
            ghcr.io/chksm/blstatus:latest
            ghcr.io/chksm/blstatus:${{ steps.vars.outputs.sha_short }}
            ghcr.io/chksm/blstatus:${{ steps.changelog.outputs.version }}

      - name: Push Docker images to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            chksm/blstatus:latest
            chksm/blstatus:${{ steps.vars.outputs.sha_short }}
            chksm/blstatus:${{ steps.changelog.outputs.version }}
          context: .

      - name: Push Docker images to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/chksm/blstatus:latest
            ghcr.io/chksm/blstatus:${{ steps.vars.outputs.sha_short }}
            ghcr.io/chksm/blstatus:${{ steps.changelog.outputs.version }}
          context: .
