name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          version_file: version.json

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            # Docker Hub
            chksm/blstatus:latest
            chksm/blstatus:${{ steps.vars.outputs.sha_short }}
            chksm/blstatus:${{ steps.changelog.outputs.version }}
          
            # GitHub Container Registry 
            ghcr.io/ChecksumDev/blstatus:latest
            ghcr.io/ChecksumDev/blstatus:${{ steps.vars.outputs.sha_short }}
            ghcr.io/ChecksumDev/blstatus:${{ steps.changelog.outputs.version }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}