name: Docker Image CI

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          version-file: version.json

      - id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            chksm/blstatus:latest
            chksm/blstatus:${{ steps.vars.outputs.sha_short }}
            chksm/blstatus:${{ steps.changelog.outputs.version }}
              
            ghcr.io/chksm/blstatus:latest
            ghcr.io/chksm/blstatus:${{ steps.vars.outputs.sha_short }}
            ghcr.io/chksm/blstatus:${{ steps.changelog.outputs.version }}
